FROM golang:latest

WORKDIR /app/centralnaBiblioteka

COPY ./backend/centralnaBiblioteka/go.mod ./backend/centralnaBiblioteka/go.sum ./

RUN go mod download

COPY ./backend/centralnaBiblioteka/ .

RUN go build -o centralnaBiblioteka

EXPOSE 8080

CMD ["./centralnaBiblioteka"]

