name: Beograd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - uses: actions/checkout@v4.1.1
    - name: docker login

      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD      
    - name: Build and push bg
      run: |
        docker build -t delicanja/gradska-biblioteka-bg:latest -f ./backend/gradskaBibliotekaBG/Dockerfile .
        docker push delicanja/gradska-biblioteka-bg:latest
