apiVersion: v1
kind: PersistentVolume
metadata:
  name: centralna-biblioteka-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/backend/centralnaBiblioteka
    type: DirectoryOrCreate
