apiVersion: v1
kind: PersistentVolume
metadata:
  name: gradska-biblioteka-nis-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/backend/gradskaBibliotekaNIS
    type: DirectoryOrCreate

