apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nis-pv
  namespace: biblioteka
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db/nis
    type: DirectoryOrCreate


