apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centralna-biblioteka-pvc
spec:
  volumeName: centralna-biblioteka-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
