apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradska-biblioteka-bg-pvc
spec:
  volumeName: gradska-biblioteka-bg-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
