apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradska-biblioteka-nis-pvc
spec:
  volumeName: gradska-biblioteka-nis-pv
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
