name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - uses: actions/checkout@v4.1.1
    - name: docker login

      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD      
    - name: Build and push Docker images
      run: |
        cd ./backend/gradskaBibliotekaNS
        docker build -t delicanja/gradska-biblioteka-ns:latest -f Dockerfile .
        docker push delicanja/gradska-biblioteka-ns:latest
