name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - uses: actions/checkout@v4.1.1
    - name: docker login

      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD      
    - name: Build and push Docker images
      run: |
        docker build -t gradska-biblioteka-ns:latest -f ./backend/gradskaBibliotekaNS/Dockerfile .
        docker build -t gradska-biblioteka-bg:latest -f ./backend/gradskaBibliotekaBG/Dockerfile .
        docker build -t gradska-biblioteka-nis:latest -f ./backend/gradskaBibliotekaNIS/Dockerfile .
        docker build -t centralna-biblioteka:latest -f ./backend/centralnaBiblioteka/Dockerfile .
        docker build -t frontend:latest -f ./frontend/Dockerfile .

        docker push delicanja/gradska-biblioteka-ns:latest
        docker push delicanja/gradska-biblioteka-bg:latest
        docker push delicanja/gradska-biblioteka-nis:latest
        docker push delicanja/centralna-biblioteka:latest
        docker push delicanja/frontend:latest
